"""Initial schema.

Hand-written rather than autogenerated for the first revision: extensions,
row-level security policies and generated columns are all things Alembic's
autogenerate does not see, and getting them wrong on revision one poisons every
migration after it.

Revision ID: 0001
"""
from __future__ import annotations

import re

from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

TENANT_TABLES = [
    "threads", "messages", "contacts", "channel_accounts",
    "thread_intelligence", "ai_drafts", "content_pieces",
    "scheduled_posts", "reviews", "automations",
]


def _split_sql_statements(sql: str) -> list[str]:
    """Split SQL while preserving Postgres dollar-quoted blocks like functions."""
    statements: list[str] = []
    current: list[str] = []
    inside_dollar = None
    i = 0

    while i < len(sql):
        if inside_dollar is not None:
            tag = sql[i: i + len(inside_dollar)]
            if tag == inside_dollar:
                current.append(inside_dollar)
                i += len(inside_dollar)
                inside_dollar = None
                continue
            current.append(sql[i])
            i += 1
            continue

        if sql.startswith("--", i):
            end = sql.find("\n", i)
            if end == -1:
                end = len(sql)
            i = end
            continue

        if sql.startswith("/*", i):
            end = sql.find("*/", i + 2)
            if end == -1:
                break
            i = end + 2
            continue

        if sql[i] == "$":
            match = re.match(r"\$[A-Za-z_]*\$", sql[i:])
            if match:
                token = match.group(0)
                current.append(token)
                inside_dollar = token
                i += len(token)
                continue

        if sql[i] == ";":
            statement = "".join(current).strip()
            if statement:
                statements.append(statement + ";")
            current = []
            i += 1
            continue

        current.append(sql[i])
        i += 1

    tail = "".join(current).strip()
    if tail:
        statements.append(tail + ";")

    return statements


def upgrade() -> None:
    with open("schema.sql", encoding="utf-8") as fh:
        sql = fh.read()
    for statement in _split_sql_statements(sql):
        op.execute(sa.text(statement))


def downgrade() -> None:
    for table in reversed(TENANT_TABLES + ["workspace_members", "workspaces", "users"]):
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
    op.execute("DROP TYPE IF EXISTS channel_kind")
